### ISSUE TITLE
bower install

### ISSUE THREAD

**Issue by geemang2000** [domchristie/juration#11]
@domchristie First off, awesome library! I've looked high and low for something like juration. 

It'd be fantastic if juration was available via bower.

**Comment by boivie** [comment]
@geemang2000 I agree, and I'll upload a PR during the week

**Comment by geemang2000** [comment]
:+1:

**Comment by domchristie** [comment]
Fixed by #12 and registered.

Thanks!

**Comment by taion** [comment]
This is really great. Thanks!

**Comment by domchristie** [comment]
You’re welcome!
